<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Rvne.ReflectiveOptions</PackageId>
    <Version>1.2.0</Version>
    <Authors>Roy Prins (Rvne)</Authors>
    <Description>Reflective options from attributes for nested node trees.</Description>
    <RepositoryUrl>https://github.com/RoyPrinsGH/Rvne.ReflectiveOptions</RepositoryUrl>
    <PackageTags>options;attributes;reflection</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

</Project>
