<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <PackageId>Rvne.ReflectiveOptions</PackageId>
    <Version>2.1.1</Version>
    <Authors>Roy Prins (Rvne)</Authors>
    <Description>Reflective options from attributes for nested node trees.</Description>
    <RepositoryUrl>https://github.com/RoyPrinsGH/Rvne.ReflectiveOptions</RepositoryUrl>
    <PackageTags>options;attributes;reflection</PackageTags>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <GeneratePackageOnBuild>false</GeneratePackageOnBuild>
    <IncludeSymbols>true</IncludeSymbols>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
  </PropertyGroup>

  <PropertyGroup>
    <TargetFrameworks>net8.0;net10.0</TargetFrameworks>
    <LangVersion>14.0</LangVersion>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <None Include="..\README.md" Pack="true" PackagePath="\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Rvne.ReflectiveOptions.Generators\Rvne.ReflectiveOptions.Generators.csproj"
                      OutputItemType="Analyzer"
                      ReferenceOutputAssembly="false"
                      PrivateAssets="all" />
  </ItemGroup>

  <PropertyGroup>
    <TargetsForTfmSpecificContentInPackage>
      $(TargetsForTfmSpecificContentInPackage);_PackSourceGenerator
    </TargetsForTfmSpecificContentInPackage>
  </PropertyGroup>

  <Target Name="_PackSourceGenerator">
    <ItemGroup>
      <TfmSpecificPackageFile Include="..\Rvne.ReflectiveOptions.Generators\bin\$(Configuration)\netstandard2.0\Rvne.ReflectiveOptions.Generators.dll"
                              PackagePath="analyzers/dotnet/cs"
                              Visible="false" />
    </ItemGroup>
  </Target>

</Project>
