using System.Text;
using Microsoft.CodeAnalysis;
using Microsoft.CodeAnalysis.CSharp.Syntax;
using Microsoft.CodeAnalysis.Text;

namespace Rvne.ReflectiveOptions.Generators;

[Generator(LanguageNames.CSharp)]
public sealed class ReflectiveOptionAttributesGenerator : IIncrementalGenerator
{
    private const string GenerateAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.GenerateReflectiveOptionsAttribute";

    private const string ApplicableOnAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.ApplicableOnAttribute";

    private const string InheritedAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.InheritedAttribute";

    private const string AllowMultipleAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.AllowMultipleAttribute";

    private const string AliasAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.AliasAttribute";

    private const string IgnoreAttributeMetadataName
        = "Rvne.ReflectiveOptions.Attributes.IgnoreAttribute";

    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        IncrementalValuesProvider<INamedTypeSymbol> generateMarkedTypes = context.SyntaxProvider
            .ForAttributeWithMetadataName(
                GenerateAttributeMetadataName,
                static (node, _) => node is ClassDeclarationSyntax,
                static (ctx, _) => (INamedTypeSymbol)ctx.TargetSymbol);

        context.RegisterSourceOutput(generateMarkedTypes, static (spc, optionsType) =>
        {
            string source = GenerateAttributesForOptionsType(optionsType);
            spc.AddSource(GetFileNameForOptionsType(optionsType), SourceText.From(source, Encoding.UTF8));
        });
    }

    private static string GetFileNameForOptionsType(INamedTypeSymbol optionsType)
    {
        string safeName = optionsType
            .ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat)
            .Replace("global::", string.Empty)
            .Replace('.', '_')
            .Replace('+', '_')
            .Replace('<', '_')
            .Replace('>', '_')
            .Replace(',', '_');

        return $"{safeName}.ReflectiveOptionAttributes.g.cs";
    }

    private static string GenerateAttributesForOptionsType(INamedTypeSymbol optionsType)
    {
        string? containingNamespace = optionsType.ContainingNamespace.IsGlobalNamespace
            ? null
            : optionsType.ContainingNamespace.ToDisplayString();

        string optionsTypeName = optionsType.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        GenerationOptionsSpec generationOptions = ResolveGenerationOptions(optionsType);

        IEnumerable<IPropertySymbol> properties = optionsType.GetMembers()
            .OfType<IPropertySymbol>()
            .Where(static property => property is { IsStatic: false, SetMethod: not null })
            .Where(static property => property.DeclaredAccessibility == Accessibility.Public)
            .Where(static property => !IsIgnored(property));

        string namespaceBlock = containingNamespace is null
            ? string.Empty
            : $$"""
              namespace {{containingNamespace}};

              """;

        string attributeBlocks = string.Join(
            "\n",
            properties
                .Select(property =>
                {
                    string propertyName = GetNameFor(property);

                    if (string.IsNullOrWhiteSpace(propertyName))
                    {
                        return string.Empty;
                    }

                    string accessibilityKeyword = IsPubliclyAccessible(optionsType) && IsPubliclyAccessible(property.Type)
                        ? "public"
                        : "internal";

                    return GenerateAttributePair(
                        optionsTypeName,
                        generationOptions,
                        property,
                        propertyName,
                        accessibilityKeyword);
                })
                .Where(static block => !string.IsNullOrWhiteSpace(block)));

        return $$"""
                 // <auto-generated />
                 #nullable enable
                 {{namespaceBlock}}{{attributeBlocks}}
                 """;
    }

    private static string GenerateAttributePair(
        string optionsTypeName,
        GenerationOptionsSpec generationOptions,
        IPropertySymbol property,
        string baseName,
        string accessibilityKeyword)
    {
        string memberName = property.Name;
        string memberTypeName = property.Type.ToDisplayString(SymbolDisplayFormat.FullyQualifiedFormat);

        string attributeTargetsExpression = GenerationTargetToAttributeTargetsLiteral(generationOptions.GenerationTarget);
        string inheritedLiteral = generationOptions.Inherited ? "true" : "false";
        string allowMultipleLiteral = generationOptions.AllowMultiple ? "true" : "false";

        string staticAttribute = $$"""
            [global::System.AttributeUsage(
                {{attributeTargetsExpression}},
                AllowMultiple = {{allowMultipleLiteral}},
                Inherited = {{inheritedLiteral}})]
            {{accessibilityKeyword}} sealed class {{baseName}}Attribute({{memberTypeName}} value)
                : global::Rvne.ReflectiveOptions.Attributes.ReflectiveOptionAttribute<{{optionsTypeName}}, {{memberTypeName}}>(nameof({{optionsTypeName}}.{{memberName}}), value)
            {
            }
            """;

        string derivedAttribute = $$"""
            [global::System.AttributeUsage(
                {{attributeTargetsExpression}},
                AllowMultiple = {{allowMultipleLiteral}},
                Inherited = {{inheritedLiteral}})]
            {{accessibilityKeyword}} sealed class Derived{{baseName}}Attribute(string methodName)
                : global::Rvne.ReflectiveOptions.Attributes.DerivedReflectiveOptionAttribute<{{optionsTypeName}}, {{memberTypeName}}>(nameof({{optionsTypeName}}.{{memberName}}), methodName)
            {
            }
            """;

        return $"{staticAttribute}\n\n{derivedAttribute}";
    }

    private static string GetNameFor(IPropertySymbol property)
    {
        AttributeData? aliasAttribute = property.GetAttributes()
            .FirstOrDefault(static attribute => MatchesAttribute(attribute, AliasAttributeMetadataName));

        string? alias = aliasAttribute?.ConstructorArguments.FirstOrDefault().Value as string;

        return string.IsNullOrWhiteSpace(alias)
            ? property.Name
            : alias!;
    }

    private static bool IsIgnored(ISymbol symbol)
        => symbol.GetAttributes().Any(attribute => MatchesAttribute(attribute, IgnoreAttributeMetadataName));

    private static bool MatchesAttribute(AttributeData attribute, string metadataName)
    {
        string? attributeName = attribute.AttributeClass?.ToDisplayString();
        if (attributeName is null)
        {
            return false;
        }

        return string.Equals(attributeName, metadataName, StringComparison.Ordinal)
            || string.Equals(attributeName, $"global::{metadataName}", StringComparison.Ordinal);
    }

    private static GenerationOptionsSpec ResolveGenerationOptions(INamedTypeSymbol optionsType)
    {
        GenerationOptionsSpec spec = new();

        foreach (AttributeData attribute in optionsType.GetAttributes())
        {
            if (MatchesAttribute(attribute, ApplicableOnAttributeMetadataName)
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is not null)
            {
                spec.GenerationTarget = MapOpaqueGenerationTarget(attribute.ConstructorArguments[0].Value!);
                continue;
            }

            if (MatchesAttribute(attribute, InheritedAttributeMetadataName)
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is bool inheritedValue)
            {
                spec.Inherited = inheritedValue;
                continue;
            }

            if (MatchesAttribute(attribute, AllowMultipleAttributeMetadataName)
                && attribute.ConstructorArguments.Length > 0
                && attribute.ConstructorArguments[0].Value is bool allowMultipleValue)
            {
                spec.AllowMultiple = allowMultipleValue;
            }
        }

        return spec;
    }

    private static GenerationTarget MapOpaqueGenerationTarget(object rawValue)
    {
        try
        {
            if (rawValue is GenerationTarget target)
            {
                return target;
            }
            else
            {
                return (GenerationTarget)Convert.ToInt32(rawValue, System.Globalization.CultureInfo.InvariantCulture);
            }
        }
        catch
        {
            return GenerationTarget.All;
        }
    }

    private static string GenerationTargetToAttributeTargetsLiteral(GenerationTarget target)
        => target switch
        {
            GenerationTarget.Class => "global::System.AttributeTargets.Class",
            GenerationTarget.Member => "global::System.AttributeTargets.Property | global::System.AttributeTargets.Field",
            _ => "global::System.AttributeTargets.Class | global::System.AttributeTargets.Property | global::System.AttributeTargets.Field",
        };

    // TODO: Explain needs to be kept in sync
    private enum GenerationTarget
    {
        Class = 0,
        Member = 1,
        All = 2
    }

    private record GenerationOptionsSpec
    {
        public GenerationTarget GenerationTarget = GenerationTarget.All;
        public bool Inherited = false;
        public bool AllowMultiple = false;
    }

    private static bool IsPubliclyAccessible(ITypeSymbol typeSymbol)
        => typeSymbol switch
        {
            IArrayTypeSymbol arrayType => IsPubliclyAccessible(arrayType.ElementType),
            INamedTypeSymbol namedType => IsPubliclyAccessibleNamedType(namedType),
            _ => typeSymbol.DeclaredAccessibility == Accessibility.Public
        };

    private static bool IsPubliclyAccessibleNamedType(INamedTypeSymbol namedType)
    {
        if (namedType.DeclaredAccessibility != Accessibility.Public)
        {
            return false;
        }

        if (namedType.ContainingType is not null && !IsPubliclyAccessibleNamedType(namedType.ContainingType))
        {
            return false;
        }

        foreach (ITypeSymbol typeArgument in namedType.TypeArguments)
        {
            if (!IsPubliclyAccessible(typeArgument))
            {
                return false;
            }
        }

        return true;
    }
}
